### ISSUE TITLE
Limiting the information printed when SetReportCaller is true 

### ISSUE THREAD

**Issue by anoop-nair** [sirupsen/logrus#865] opened 2018-11-19 07:01 UTC
When `SetReportCaller` is `true`, the log has the full file path (starting at root) and then also the method name as below
`INFO[2018-11-19 10:15:34]/Users/anoop/goworkspace/src/go-sample-app/pack/some_doer.go:22 go-sample-app/pack.DoSomething() Doing something` 

Is it possible to restrict the file name to start only from the application's root directory and not print the method name? Below is an example of what I am looking for.
`INFO[2018-11-19 10:15:34]go-sample-app/pack/some_doer.go:22 Doing something `

**Comment by dgsb** [comment] 2018-11-22 06:01
At this time the current implementation does not provide a way to configure the length of the path to use in the output.

**Comment by cacheflux** [comment] 2019-02-08 20:12
You can partially get rid of the path by passing trimpath flags to go build:
```
go build \
	-gcflags="all=-trimpath=${GOPATH}" \
	-asmflags "all=-trimpath=${GOPATH}" \
	./...
```

**Comment by dgsb** [comment] 2019-02-10 13:14
duplicate of #887

**Closed by dgsb** 2019-02-10 13:14 UTC
Labels: enhancement
