### ISSUE TITLE
Add possibility to create default Fields.

### ISSUE THREAD

**Issue by PurpureGecko** [sirupsen/logrus#444] opened 2016-11-15 12:56 UTC
There are many things, what must be in every entry. For example appname or hostname.
This can be added to Logger or to Formatters. I think modify Formatters is better decision.

**Comment by dclendenan** [comment] 2016-12-03 01:23
I've had similar thoughts, and used this functionality in other loggers (in other languages). I'll look into this once my current PR is merged.

**Comment by bonds0097** [comment] 2017-01-09 02:16
Does passing around a `logrus.FieldLogger` not satisfy this requirement?

**Comment by stevvooe** [comment] 2017-01-10 20:10
@PurpureGecko Do you have a proposed design? PR?

**Comment by stevvooe** [comment] 2017-01-10 20:12
Actually, this is fairly easily done by passing around a `log.Entry` populated with the fields:

```
logger := logrus.WithField("default", "foo")
logger.Info("will have default")
```

This has been sufficient in a number of applications. You can even store the logger in a context to make it accessible in cross-cutting areas.

Closing this. If this is insufficient, please propose a solution with a PR.

**Closed by stevvooe** 2017-01-10 20:12 UTC

**Comment by mcuadros** [comment] 2017-10-02 07:27
The problem is that with the current implementation you can't add default fields to the standard logger.

**Comment by arieroos** [comment] 2021-05-03 07:59
This how I added a default field without having to rewrite all my logging code:
```go
package main

import (
	log "github.com/sirupsen/logrus"
)

type customLogger struct {
	defaultField string
	formatter    log.Formatter
}

func (l customLogger) Format(entry *log.Entry) ([]byte, error) {
	entry.Data["field_name"] = l.defaultField
	return l.formatter.Format(entry)
}

func main() {
	log.SetFormatter(customLogger{
		defaultField: "defaultValue",
		formatter:    log.StandardLogger().Formatter,
	})
	log.Info("test")
}
```
