### ISSUE TITLE
Log filename and line number

### ISSUE THREAD

**Issue by gust1n** [sirupsen/logrus#63] opened 2014-09-22 21:40 UTC
Both stdlib package log and many other logging frameworks are supporting this (e.g. https://github.com/inconshreveable/log15). Am I missing how to enable it or is it not supported?

**Comment by cep21** [comment] 2015-03-13 17:58
I solve this in a performant manner by doing the following:

```go
var log *logrus.Logger

func init() {
	log = mylog.NewLogger()
}


func NewLogger() *logrus.Logger {
	_, file, _, ok := runtime.Caller(1)
	if !ok {
		file = "unknown"
	}
	inst := &logInstance{
		innerLogger: ret,
		file:        filepath.Base(file),
	}
	ret.Hooks.Add(inst)
    return ret
}
```

logInstance is a hook that adds "file" to the log entry.  This saves me calling runtime.Caller each time I log a message while still having code that does

```go
  log.WithField()....Info()
```

**Comment by chreble** [comment] 2015-06-04 15:40
+1 it's a MUST-HAVE, and saying "completely API compatible with the standard library logger" in the README is wrong as we have that feature in the standard Go logger (SetFlags) http://golang.org/pkg/log/#SetFlags

**Comment by gonzaloserrano** [comment] 2015-06-11 15:39
+1

**Comment by Sirupsen** [comment] 2015-06-14 14:09
Perhaps someone take a closer look at `SetFlags` implementation and port it to `logrus`? Currently all the implementations I've seen rely on hardcoding number of stack frames which is not very portable and doesn't work in some cases.

**Comment by chreble** [comment] 2015-06-15 06:16
@Sirupsen,  I can definitely have a look :)

**Comment by Sirupsen** [comment] 2015-06-15 11:56
@chreble awesome, let me know what you find!

**Comment by dmlyons** [comment] 2015-06-23 15:57
@Sirupsen unfortunately, the `SetFlags` implementation in the standard library uses a (sort of) hardcoded number of stack frames: http://golang.org/src/log/log.go#L130.  Each exported output function, such as Println, passes `callDepth` like this: http://golang.org/src/log/log.go#L169.

Is this such a big deal to implement in logrus?

**Comment by Sirupsen** [comment] 2015-07-06 15:50
@dmlyons no it's not, I've just not needed this myself and haven't seen an implementation that hasn't failed on different platforms.

**Comment by davisford** [comment] 2015-08-18 17:09
Has anyone resolved this in a reasonable way?  I just want the filename and line number.  I'd also prefer to be able to configure it to only print on specific levels (e.g. err, panic, warn)

**Comment by gonzaloserrano** [comment] 2015-08-18 17:58
We have wrapped the stuff we most use from logrus with the file information, i don't know if you will find it useful or not but here you are https://gist.github.com/gonzaloserrano/d360c1b195f7313b6d19

**Comment by ryanwalls** [comment] 2015-08-22 00:31
+1

**Comment by ephemeralsnow** [comment] 2015-08-25 07:04
+1

**Comment by santagada** [comment] 2015-09-01 14:22
I will try to take a swing at it, as @dmlyons said it is pretty straightforward to implement.

**Comment by leonlee** [comment] 2015-09-17 05:41
+1

**Comment by AkihiroSuda** [comment] 2015-10-07 08:04
+1

**Comment by davisford** [comment] 2015-10-10 02:23
My solution was to use https://github.com/inconshreveable/log15

**Comment by sundarv85** [comment] 2015-11-05 13:08
+1

**Comment by ryanwalls** [comment] 2015-11-10 14:22
Thanks @davisford.  That's what I did as well.

**Comment by kdar** [comment] 2015-11-25 19:40
I'm kind of confused why you couldn't just make your formatter, or wrap a formatter you already use, accomplish this. I do this for our production systems. The only downside is if logrus' internals change, it could possibly change the callstack. But, you can catch this early if you make a testcase for your formatter.

I would rather logrus not implement this by default because it has performance implications. Unless you provide a way for people to disable it if they don't need it, which just adds another API.

**Comment by jeffizhungry** [comment] 2015-11-29 08:38
The cleanest solution I came up with was just to mimic the standard logger with my own logging interface. Since the caller info is registered there, there should be no issues with the call stack changing. Other than that I tried to keep the interface exactly the same as Sirupsen/logrus/logger.go so applications can easily switch back to this logger. 

https://github.com/jeffizhungry/logrus

**Comment by rand99** [comment] 2015-12-14 09:20
Hi, this might help
https://github.com/facebookgo/stack

**Comment by andrewrgoss** [comment] 2016-01-13 21:05
+1

**Comment by omidnikta** [comment] 2016-01-16 11:42
Why not using the runtime package

import (
    "runtime"
    log "github.com/Sirupsen/logrus"
)

func main() {
	pc, file, line, ok := runtime.Caller(0)
	log.WithFields(log.Fields{
		"Program Counter": pc,
		"File":            file,
		"Line":            line,
		"Recoverable":     ok,
	}).Debug("Some logging info")
}

**Comment by omidnikta** [comment] 2016-01-17 08:53
I proposed a merge that can log file name and line numbers. It is located in the show-file-line branch of the clone https://github.com/omidnikta/logrus

One can use ShowFileLine(bool) to enable/disable logging file-line.

**Comment by ilgooz** [comment] 2016-03-05 21:01
we need this ASAP, anyone working on this?

**Comment by boyand** [comment] 2016-03-08 22:16
+1

**Comment by apriendeau** [comment] 2016-03-08 22:40
@omidnikta where is that PR?

**Comment by MarkSonghurst** [comment] 2016-03-08 22:41
+1

**Comment by NishantMF** [comment] 2016-03-22 08:37
+1

**Comment by mehdioa** [comment] 2016-03-27 09:46
@apriendeau The clone is in https://github.com/omidnikta/logrus, but when I checked correctly the source of logrus, it is not thread safe at all, but the pull request is OK anyway. That is why I started https://github.com/omidnikta/nlog which is a minimal thread safe logger.

**Comment by omidnikta** [comment] 2016-03-27 09:59
@apriendeau The pull request is
#312

But when I checked correctly the source of logrus, it is not thread safe at all, but the pull request is OK anyway. That is why I started https://github.com/omidnikta/nlog which is a minimal thread safe logger.

**Comment by h0tbird** [comment] 2016-04-11 19:51
+1

**Comment by cjrd** [comment] 2016-04-15 21:13
+1

**Comment by vishnuone** [comment] 2016-04-27 07:26
+1

**Comment by ZhangZhenhua** [comment] 2016-05-13 07:31
+1

**Comment by kpurdon** [comment] 2016-05-13 14:09
To avoid any more `+1` comments (which BTW GitHub implemented reactions to avoid this) @apriendeau has this work done in a PR that is being reviewed right now.

https://github.com/Sirupsen/logrus/pull/349

**Comment by jinleileiking** [comment] 2016-07-21 12:40
-_-...... 2016.7.21 this feature remains fail..

**Comment by renke** [comment] 2016-07-22 18:50
I am using this as workaround while developing

```
type ContextHook struct {
}

func (hook ContextHook) Levels() []log.Level {
	return log.AllLevels
}

func (hook ContextHook) Fire(entry *log.Entry) error {
	if pc, file, line, ok := runtime.Caller(8); ok {
		funcName := runtime.FuncForPC(pc).Name()

		entry.Data["file"] = path.Base(file)
		entry.Data["func"] = path.Base(funcName)
		entry.Data["line"] = line
	}

	return nil
}

func main() {
	log.AddHook(ContextHook{})
        …
}
```

**Comment by jinleileiking** [comment] 2016-07-23 03:34
@renke seems can work

**Comment by roylou** [comment] 2016-07-28 23:11
Modified @renke's workaround a bit so it works for WithField.

```go
type ContextHook struct{}

func (hook ContextHook) Levels() []logrus.Level {
	return logrus.AllLevels
}

func (hook ContextHook) Fire(entry *logrus.Entry) error {
	pc := make([]uintptr, 3, 3)
	cnt := runtime.Callers(6, pc)

	for i := 0; i < cnt; i++ {
		fu := runtime.FuncForPC(pc[i] - 1)
		name := fu.Name()
		if !strings.Contains(name, "github.com/Sirupsen/logrus") {
			file, line := fu.FileLine(pc[i] - 1)
			entry.Data["file"] = path.Base(file)
			entry.Data["func"] = path.Base(name)
			entry.Data["line"] = line
			break
		}
	}
	return nil
}

func main() {
	logrus.AddHook(ContextHook{})
....
}
```

It's more expensive however since it allocates memory every time.

**Comment by falanjones** [comment] 2016-08-09 15:45
My solution is to call a function on each logging instance.
That way you can take it out for entries that are performance sensitive.
```go
func Locate(fields logrus.Fields) logrus.Fields {
	_, path, line, ok := runtime.Caller(1)
	if ok {
		_, file := filepath.Split(path)
		fields["file"] = file
		fields["line"] = line
	}
	return fields
}
...
	log.WithFields(Locate(logrus.Fields{
		"url": url,
	})).Info("Bound management service")
```

**Comment by ilakhmedov** [comment] 2016-08-11 21:40
Is it still not printing the stacktrace? Any way to get output like in std error stacktrace?

**Comment by startover** [comment] 2016-08-20 11:29
+1

**Comment by zhl11b** [comment] 2016-08-21 05:23
my slotion is add a hook
[github.com/zhl11b/logrus-hook-caller](url)
`// CallerHook 需要的钩子

type CallerHook struct {

}



// Fire 实现

func (hook *CallerHook) Fire(entry *logrus.Entry) error {

	if len(entry.Data) == 0 {

		entry.Data["caller"] = hook.caller2()

	} else {

		entry.Data["caller"] = hook.caller()

	}



	return nil

}`

check entry.data make sure get a right caller

**Comment by JReyLBC** [comment] 2016-08-23 17:54
In case no one has seen the Go 1.7 release notes yet, a new function was added to the runtime package which has performance improvements over FuncForPC: 

> The new function CallersFrames translates a PC slice obtained from Callers into a sequence of frames corresponding to the call stack. This new API should be preferred instead of direct use of FuncForPC, because the frame sequence can more accurately describe call stacks with inlined function calls.
[Go 1.7 release notes](https://golang.org/doc/go1.7#runtime)

Here's the godoc: https://golang.org/pkg/runtime/#CallersFrames

**Comment by Gurpartap** [comment] 2016-10-09 20:47
With cues from here and facebookgo/stack's structs combining file, line and func name, I've written a hook that is working well for me (and I don't see why it wouldn't for anyone else): https://github.com/Gurpartap/logrus-stack 🎯. You can get the last caller as well as the full stack trace.

There wasn't a solution that worked in all (most?) cases, so I wrote it. You have to skip frames differently when there's WithField, and then you have to filter out logrus's own frames. And then there's the formatting. Hope the hook helps others.

**Comment by 178inaba** [comment] 2016-11-25 05:11
A race condition occurs when writing to entry.Data inside the hook.
Possible to prevent the race condition from occurring?

Race condition point:

```go
// Inside hook.
entry.Data["xxx"] = "xxx"
// https://github.com/Sirupsen/logrus/blob/a437dfd2463eaedbec3dfe443e477d3b0a810b3f/text_formatter.go#L61
var keys []string = make([]string, 0, len(entry.Data))
```

**Comment by hwsdien** [comment] 2017-01-12 07:13
+1

**Comment by davidradunz** [comment] 2017-01-13 01:18
+1

**Comment by natdm** [comment] 2017-01-20 17:05
I was able to make my own functionality with what they have currently and borrowing code from others that have solved their own issues with this. I didn't like having to deorate each caller with a wrapped function, so I made my own `Decorate(logger *logrus.Entry) func() *logrus.Entry` that works for me.

```go
package logger

import (
	"fmt"
	"net/http"
	"runtime"
	"strings"

	"github.com/Sirupsen/logrus"
)

/* truncated */

// Decorate appends line, file and function context to the logger and returns a function to call before
// each log
func Decorate(logger *logrus.Entry) func() *logrus.Entry {
	return func() *logrus.Entry {
		if pc, f, line, ok := runtime.Caller(1); ok {
			fnName := runtime.FuncForPC(pc).Name()
			file := strings.Split(f, "mobilebid")[1]
			caller := fmt.Sprintf("%s:%v %s", file, line, fnName)

			return logrus.WithField("caller", caller)
		}
		return logger
	}
}

// Log appends line, file and function context to the logger
func Log() *logrus.Entry {
	if pc, f, line, ok := runtime.Caller(1); ok {
		fnName := runtime.FuncForPC(pc).Name()
		file := strings.Split(f, "mobilebid")[1]
		caller := fmt.Sprintf("%s:%v %s", file, line, fnName)

		return logrus.WithField("caller", caller)
	}
	return &logrus.Entry{}
}
```

In use:
```go
// Using context
logctx := logger.Decorate(WithField("remote_address", conn.RemoteAddr()))
logctx().WithField("test", "works").Info("it works fine")

// Standard logging
logger.Log().WithError(err).Error("error upgrading websocket")

// With multiple fields
logger.Log().WithFields(logrus.Fields{
    "field":  "something",
    "field2": "something else",
}).WithError(err).Error("error upgrading websocket")
```

**Comment by flyzhang007** [comment] 2017-02-04 03:56
will this function to be added

**Comment by lnshi** [comment] 2017-03-02 03:45
after three years, still doesn't have this functionality?

**Comment by wadelee1986** [comment] 2017-03-02 09:57
+1

**Comment by leonzhan** [comment] 2017-03-08 06:53
Same question as @lnshi , just tell me why:)

**Comment by mohanraj-r** [comment] 2017-03-15 18:37
Looks like there were multiple PRs aiming to fix this issue https://github.com/sirupsen/logrus/pull/349, https://github.com/sirupsen/logrus/pull/388

Looking at the PRs looks like they went nowhere even after repeated requests from authors for feedback and the authors seem to have closed the PRs themselves - probably out of frustration.

**Comment by tbarbugli** [comment] 2017-03-25 19:01
Since this is probably never going to be added or merged, it would be great if the authors could give their blessing to a plugin or a workaround to achieve this.

ps. Thank you for the awesome library!

**Comment by Depado** [comment] 2017-08-01 08:35
Any news on this ? 😃

**Comment by jinghzhu** [comment] 2017-08-03 06:55
It's very important to log filename and line number. This can make it easier for engineers to debug.

Could you please let us know whether this feature will be implemented?

Thanks a lot.

**Comment by Depado** [comment] 2017-08-03 14:30
I don't know if that's helpful but the prometheus team [did it like this](https://github.com/prometheus/common/blob/master/log/log.go#L234)

**Comment by bonly** [comment] 2017-09-15 08:29
+1

**Comment by RenathoAzevedo** [comment] 2017-11-16 18:08
is there a solution merged to this ?

**Comment by damekr** [comment] 2017-11-27 20:38
Actually I found a workaround not full but something for this, using package: 
github.com/x-cray/logrus-prefixed-formatter

And in code it looks like:
`var log = logrus.WithFields(logrus.Fields{"prefix": "main"})

func init() {
	logrus.SetFormatter(&prefixed.TextFormatter{})
	logrus.SetLevel(logrus.DebugLevel)
}`

After that you just need to add in each package somethink like:
`var log = logrus.WithFields(logrus.Fields{"prefix": "package"})`

In logs it looks like:
`[0000]  INFO cmds: Sending ping to server: 127.0.0.1
[0000] DEBUG client: Establishing grpc connection with: 127.0.0.1
`
Hopefully it helps :)

**Comment by mihaitodor** [comment] 2017-12-06 21:26
@damekr How does that solve the issue of logging the file name and line number?

**Comment by damekr** [comment] 2017-12-07 07:20
@mihaitodor Instead of {"prefix": "main"} you can use filename. It is not a full solution as I said, but can help a bit to solve the problem.

**Comment by mihaitodor** [comment] 2017-12-07 11:49
Ah, I see. Thanks!

**Comment by RenathoAzevedo** [comment] 2017-12-07 11:56
@damekr I'm using  filename. When you say that is not a full solution, what do you mean ?
`filenameHook := filename.NewHook()`
`filenameHook.Field = filenameField`
`log.AddHook(filenameHook)`

`{"level":"info","message":"test","origem":"mobileServer/server.go:65","time":"2017-12-07T09:54:28.449479945-02:00"}`

It works fine for me. Should I be aware of something ?

**Comment by damekr** [comment] 2017-12-07 12:44
@RenathoAzevedo No, it's just another way to do that :)

**Comment by RenathoAzevedo** [comment] 2017-12-07 12:52
@damekr Thank you, I'm still wating for 'native' solution from logrus.

**Comment by mclxly** [comment] 2018-01-05 07:36
@roylou
Alwarys print "...line=189"
![image](https://user-images.githubusercontent.com/1973671/34599548-f13e599a-f22d-11e7-982d-a3987907645a.png)

So I changed one line:
![image](https://user-images.githubusercontent.com/1973671/34599557-08039596-f22e-11e7-9872-c61a6fc9bdfe.png)

Works for me now:
![image](https://user-images.githubusercontent.com/1973671/34599584-1e323322-f22e-11e7-8abc-9ea0699844ba.png)

**Comment by miguelmota** [comment] 2018-01-28 01:27
Dear logrus maintainers, it's self-evident that the community would like a simple and critical feature such as filename and line number logging to be native in the logrus library. It's much needed and we'd all greatly appreciate this feature. Thanks!

**Comment by spothanis** [comment] 2018-02-03 00:59
+1

**Comment by wantg** [comment] 2018-02-03 13:12
package main

import (
	"encoding/json"
	"runtime"

	log "github.com/sirupsen/logrus"
)

type MyJSONFormatter struct {
	Level string `json:"level"`
	Info  string `json:"info"`
	Msg   string `json:"msg"`
	Time  string `json:"time"`
	File  string `json:"file"`
	Line  int    `json:"line"`
}

func (f *MyJSONFormatter) Format(entry *log.Entry) ([]byte, error) {

	logrusJF := &(log.JSONFormatter{})
	bytes, _ := logrusJF.Format(entry)

	myF := MyJSONFormatter{}
	json.Unmarshal(bytes, &myF)
	_, file, no, _ := runtime.Caller(7)
	myF.File = file
	myF.Line = no

	return json.Marshal(myF)
}

func main() {
	log.SetFormatter(&MyJSONFormatter{})
	log.Infoln("fire")
}

**Comment by halink0803** [comment] 2018-02-10 05:34
So any updated on this feature? Is this available now? I walk through comments, it seems nothing is official yet?

**Comment by andytsnowden** [comment] 2018-02-13 16:52
@RenathoAzevedo in the example where you mention filename, where is that package? If possible could you post a full example of your solution?

**Comment by RenathoAzevedo** [comment] 2018-02-13 17:08
Hello @andytsnowden, I'm using  filename hook from https://github.com/onrik/logrus, It's quite simple to use.

```filenameHook := filename.NewHook()
filenameHook.Field = "source"
logrus.AddHook(filenameHook) ```

**Comment by shuge** [comment] 2018-02-26 07:23
Jesus Christ, it is still doesn't supports a common feature after four years..

**Comment by stevvooe** [comment] 2018-02-28 22:00
> Jesus Christ, it still doesn't supports a common feature after four years.

Please keep it civil. I think the maintainers voiced valid concerns and 

I have reviewed one or two PRs that propose adding this feature and most seemed to add a cost whether your using it or not. If there is a PR with this functionality, that doesn't create a performance cost, point me to and I'll have a look.

I think https://github.com/sirupsen/logrus/pull/450/ was looking promising, although it may need the additional file and line number.

**Comment by ypapax** [comment] 2018-03-08 06:09
I am using https://github.com/onrik/logrus as well for printing file names and lines:

```golang
package main

import (
	"github.com/onrik/logrus/filename"
	log "github.com/sirupsen/logrus"
)

func main(){
	log.AddHook(filename.NewHook())
        ...
        log.Println(something)
        
```
logs look like this:
```
INFO[0000] 404 Not Found                                 source="scraper/main.go:46"
INFO[0000] 404 Not Found                                 source="scraper/main.go:46"
```

**Comment by dclendenan** [comment] 2018-03-08 23:58
#450 shouldn't add a cost unless the flag is set to enable the extra data.  There's some cost in gathering the data, but we've been working from my fork in production for over a year now with no issues seen.  I am looking forward to getting back on mainline Logrus someday, though :)

If there's more data desired than what I've added there, we can of course continue to evolve...

@stevvooe I've resolved the merge conflict in that PR, FYI.

**Comment by Niondir** [comment] 2018-07-13 16:55
I would also appreciate this feature (as everybody else does) there are so many proposals and pull requests. Whats actually blocking this issue?

Are you just afraid of cross platform bugs?

**Comment by dgsb** [comment] 2018-07-24 05:36
I will have a look at this pr soon.

**Comment by githubvip1207** [comment] 2018-08-16 09:10
4 year open-issues ~~~

**Comment by Jing-Li** [comment] 2018-08-17 05:28
+1, any update here?  I check the solutions in the comments. I want to get the official answer about the hook, is there some other concern? Like performance issues?

**Comment by andytsnowden** [comment] 2018-08-17 05:37
@Jing-Li I've been using the solution posted here: https://github.com/sirupsen/logrus/issues/63#issuecomment-365334562 in production for about 6 months now and haven't really had any issues at all.  In my use-case we emit about 10m lines of logging daily and I really haven't seen logging be a "slow" point.

**Comment by dgsb** [comment] 2018-10-16 11:43
up

**Comment by rfay** [comment] 2018-10-28 22:02
Yay, but please do provide instructions here (or in docs) on how #850 gives us file and line number. It's certainly not apparent from a quick view.

**Comment by miguelmota** [comment] 2018-10-28 22:19
Here's how to have logrus log the filename and line number with the latest release. Basically just add `log.SetReportCaller(true)` when initializing. 

Example:

```go
package main

import (
	log "github.com/sirupsen/logrus"
)

func main() {
        // Add this line for logging filename and line number!
	log.SetReportCaller(true)

	log.Println("hello world")
}
```

Output:

```bash
INFO[0000]/Users/bob/go/src/github.com/bob/test/main.go:17 main.main() hello world
```

**Comment by dgsb** [comment] 2018-10-30 06:09
@rfay the pull request contains a change in the readme which describes how to enable this feature.

**Comment by dgsb** [comment] 2018-11-03 07:04
This feature is contained in v1.2.0

**Closed** 2018-11-03 07:04 UTC
Labels: enhancement

**Comment by wesgt** [comment] 2018-11-19 16:07
> Here's how to have logrus log the filename and line number with the latest release. Basically just add `log.SetReportCaller(true)` when initializing.
> 
> Example:
> 
> ```go
> package main
> 
> import (
> 	log "github.com/sirupsen/logrus"
> )
> 
> func main() {
>         // Add this line for logging filename and line number!
> 	log.SetReportCaller(true)
> 
> 	log.Println("hello world")
> }
> ```
> 
> Output:
> 
> ```shell
> INFO[0000]/Users/bob/go/src/github.com/bob/test/main.go:17 main.main() hello world
> ```
Hi all, is there a way to cut the longest file path? like just to display the 
```shell
test/main.go:17
```
Thanks...QQ

**Comment by Jing-Li** [comment] 2018-11-21 05:17
@andytsnowden ,  

> @Jing-Li I've been using the solution posted here: [#63 (comment)](https://github.com/sirupsen/logrus/issues/63#issuecomment-365334562) in production for about 6 months now and haven't really had any issues at all. In my use-case we emit about 10m lines of logging daily and I really haven't seen logging be a "slow" point.

@andytsnowden , this help a lot, thanks.

**Comment by Wamani** [comment] 2019-03-23 02:29
> > Here's how to have logrus log the filename and line number with the latest release. Basically just add `log.SetReportCaller(true)` when initializing.
> > Example:
> > ```go
> > package main
> > 
> > import (
> > 	log "github.com/sirupsen/logrus"
> > )
> > 
> > func main() {
> >         // Add this line for logging filename and line number!
> > 	log.SetReportCaller(true)
> > 
> > 	log.Println("hello world")
> > }
> > ```
> > 
> > 
> > Output:
> > ```shell
> > INFO[0000]/Users/bob/go/src/github.com/bob/test/main.go:17 main.main() hello world
> > ```
> 
> Hi all, is there a way to cut the longest file path? like just to display the
> 
> ```shell
> INFO[0000]/test/main.go:17 main.main() hello world
> ```
> 
> Thanks...QQ

any idea on how to cut file name ?

**Comment by dgsb** [comment] 2019-03-23 13:44
@Wamani please don't comment on closed issue, because it's kind of hard to find it back.
The basic filter on the github interface doesn't show closed issues whatever how recently they have been updated. The next time open a new one, it will be easier for the maintainer to provide feedback and guidance.

That said if you want to customiza the output of the caller field you can give a specific formatting function in the CallerPrettyfier field of the JSONFormatter (https://godoc.org/github.com/sirupsen/logrus#JSONFormatter) or of the TextFormatter (https://godoc.org/github.com/sirupsen/logrus#TextFormatter).

You also have an example in the logrus repository on how to use that with the JSONFormatter here
https://github.com/sirupsen/logrus/blob/master/example_custom_caller_test.go

**Comment by miguelmota** [comment] 2019-03-26 05:56
@wesgt @Wamani 

Here's how to cut the longest file path:

```go
package main

import (
	"fmt"
	"os"
	"runtime"
	"strings"

	"github.com/sirupsen/logrus"
)

func main() {
	log := logrus.New()
	log.SetReportCaller(true)
	log.Formatter = &logrus.TextFormatter{
		CallerPrettyfier: func(f *runtime.Frame) (string, string) {
			repopath := fmt.Sprintf("%s/src/github.com/bob", os.Getenv("GOPATH"))
			filename := strings.Replace(f.File, repopath, "", -1)
			return fmt.Sprintf("%s()", f.Function), fmt.Sprintf("%s:%d", filename, f.Line)
		},
	}

	log.Println("hello world")
}
```

Output:

```bash
INFO[0000]/test/main.go:23 main.main() hello world
```

**Comment by Wamani** [comment] 2019-04-04 08:22
> @wesgt @Wamani
> 
> Here's how to cut the longest file path:
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"os"
> 	"runtime"
> 	"strings"
> 
> 	"github.com/sirupsen/logrus"
> )
> 
> func main() {
> 	log := logrus.New()
> 	log.SetReportCaller(true)
> 	log.Formatter = &logrus.TextFormatter{
> 		CallerPrettyfier: func(f *runtime.Frame) (string, string) {
> 			repopath := fmt.Sprintf("%s/src/github.com/bob", os.Getenv("GOPATH"))
> 			filename := strings.Replace(f.File, repopath, "", -1)
> 			return fmt.Sprintf("%s()", f.Function), fmt.Sprintf("%s:%d", filename, f.Line)
> 		},
> 	}
> 
> 	log.Println("hello world")
> }
> ```
> 
> Output:
> 
> ```shell
> INFO[0000]/test/main.go:23 main.main() hello world
> ```

thanks it works

**Comment by art-frela** [comment] 2019-08-22 15:51
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"os"
> 	"runtime"
> 	"strings"
> 
> 	"github.com/sirupsen/logrus"
> )
> 
> func main() {
> 	log := logrus.New()
> 	log.SetReportCaller(true)
> 	log.Formatter = &logrus.TextFormatter{
> 		CallerPrettyfier: func(f *runtime.Frame) (string, string) {
> 			repopath := fmt.Sprintf("%s/src/github.com/bob", os.Getenv("GOPATH"))
> 			filename := strings.Replace(f.File, repopath, "", -1)
> 			return fmt.Sprintf("%s()", f.Function), fmt.Sprintf("%s:%d", filename, f.Line)
> 		},
> 	}
> 
> 	log.Println("hello world")
> }
> ```

Thank a lot of!  
I am using path.Base, this is more universal, I think ;-) 

```golang
package main

import (
	"fmt"
	"path"
	"runtime"

	"github.com/sirupsen/logrus"
)

func main() {
	log := logrus.New()
	log.SetReportCaller(true)
	log.Formatter = &logrus.TextFormatter{
		CallerPrettyfier: func(f *runtime.Frame) (string, string) {
			filename := path.Base(f.File)
			return fmt.Sprintf("%s()", f.Function), fmt.Sprintf("%s:%d", filename, f.Line)
		},
	}

	log.Println("hello world")
}
`

**Comment by miguelmota** [comment] 2019-08-23 11:15
@art-frela great suggestion on using `path.Base`!

**Comment by ya0yy** [comment] 2019-10-24 06:10
@miguelmota why i not see CallerPrettyfier
```console
unknown field 'CallerPrettyfier' in struct literal of type logrus.TextFormatter
```

**Comment by saurabh-hirani** [comment] 2019-11-01 13:45
Worth mentioning that if you are using logrus JSONFormatter and you need filename and line support, there is a handy example in the codebase which adds funcname and filename. - https://github.com/sirupsen/logrus/blob/master/example_custom_caller_test.go

```
l.Formatter = &logrus.JSONFormatter{
		DisableTimestamp: true,
		CallerPrettyfier: func(f *runtime.Frame) (string, string) {
			s := strings.Split(f.Function, ".")
			funcname := s[len(s)-1]
			_, filename := path.Split(f.File)
			return funcname, filename
		},
	}
```

A slight modification to it can return line number also

```
return funcname, filename + ":" + strconv.Itoa(f.Line)
```

**Comment by bruceadowns** [comment] 2020-01-11 01:09
> Worth mentioning that if you are using logrus JSONFormatter and you need filename and line support, there is a handy example in the codebase which adds funcname and filename. - https://github.com/sirupsen/logrus/blob/master/example_custom_caller_test.go

My code ended up looking a little like this:

```
logrus.SetReportCaller(true)
formatter = &logrus.JSONFormatter{
    CallerPrettyfier: func(f *runtime.Frame) (string, string) {
        s := strings.Split(f.Function, ".")
        funcName := s[len(s)-1]
        return funcName, fmt.Sprintf("%s:%d", path.Base(f.File), f.Line)
    },
}
```

Which logs source file name, function name, and line number.

**Comment by chibby0ne** [comment] 2020-02-28 16:02
I can't reproduce this in logrus 1.4.2 using Go 1.14, I tried @art-frela snippet, and I can't reproduce it. This is my output:
```
INFO[0000]entry.go:359 github.com/sirupsen/logrus.(*Entry).Logln() hello world
```
Any ideas?

**Comment by dgsb** [comment] 2020-02-28 16:09
related to #1096

**Comment by chibby0ne** [comment] 2020-02-28 16:41
Yep it's Go 1.14 thanks @dgsb I thought I was going crazy for the last hour :+1:

**Comment by trinhhuong244** [comment] 2020-10-23 19:00
formatter := runtime.Formatter{ChildFormatter: &log.TextFormatter{
		FullTimestamp: true,
	}}
	formatter.Line = true
	log.SetFormatter(&formatter)
	log.SetOutput(os.Stdout)
	log.SetLevel(log.InfoLevel)
	log.WithFields(log.Fields{
		"file": "main.go",
	}).Info("Server is running...")
Note: import ( 	runtime "github.com/banzaicloud/logrus-runtime-formatter"
	log "github.com/sirupsen/logrus")

**Comment by kuchaguangjie** [comment] 2021-04-13 07:02
> > ```go
> > package main
> > 
> > import (
> > 	"fmt"
> > 	"os"
> > 	"runtime"
> > 	"strings"
> > 
> > 	"github.com/sirupsen/logrus"
> > )
> > 
> > func main() {
> > 	log := logrus.New()
> > 	log.SetReportCaller(true)
> > 	log.Formatter = &logrus.TextFormatter{
> > 		CallerPrettyfier: func(f *runtime.Frame) (string, string) {
> > 			repopath := fmt.Sprintf("%s/src/github.com/bob", os.Getenv("GOPATH"))
> > 			filename := strings.Replace(f.File, repopath, "", -1)
> > 			return fmt.Sprintf("%s()", f.Function), fmt.Sprintf("%s:%d", filename, f.Line)
> > 		},
> > 	}
> > 
> > 	log.Println("hello world")
> > }
> > ```
> 
> Thank a lot of!
> I am using path.Base, this is more universal, I think ;-)
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"path"
> 	"runtime"
> 
> 	"github.com/sirupsen/logrus"
> )
> 
> func main() {
> 	log := logrus.New()
> 	log.SetReportCaller(true)
> 	log.Formatter = &logrus.TextFormatter{
> 		CallerPrettyfier: func(f *runtime.Frame) (string, string) {
> 			filename := path.Base(f.File)
> 			return fmt.Sprintf("%s()", f.Function), fmt.Sprintf("%s:%d", filename, f.Line)
> 		},
> 	}
> 
> 	log.Println("hello world")
> }
> `
> ```

This lose coloring on console.

**Comment by shinebayar-g** [comment] 2022-11-27 11:19
Just for reference I came up with this to show `filename:line`. It's little bit cleaner than `f.Function` IMO.

```go
log.SetFormatter(&log.TextFormatter{
    FullTimestamp: true,
    CallerPrettyfier: func(f *runtime.Frame) (second string, first string) {
        _, b, _, _ := runtime.Caller(0)
        basepath := filepath.Dir(b)
        rel, err := filepath.Rel(basepath, f.File)
        if err != nil {
            log.Error("Couldn't determine file path\n", err)
        }
        return "", fmt.Sprintf("%s:%d", rel, f.Line)
    },
})
log.SetReportCaller(true)
```

```
INFO[2022-11-27T03:16:16-08:00]database/setup.go:31 Connected to database.
INFO[2022-11-27T03:16:16-08:00]database/setup.go:32 Running migrations.
INFO[2022-11-27T03:16:16-08:00]scheduler/task.go:17 Doing something.
```

**Comment by flyzhang007** [comment] 2022-11-27 11:20
您的邮件已收到，我会尽快查看&回复:)

**Comment by shinebayar-g** [comment] 2022-11-27 22:18
> > > ```go
> > > package main
> > > 
> > > import (
> > > 	"fmt"
> > > 	"os"
> > > 	"runtime"
> > > 	"strings"
> > > 
> > > 	"github.com/sirupsen/logrus"
> > > )
> > > 
> > > func main() {
> > > 	log := logrus.New()
> > > 	log.SetReportCaller(true)
> > > 	log.Formatter = &logrus.TextFormatter{
> > > 		CallerPrettyfier: func(f *runtime.Frame) (string, string) {
> > > 			repopath := fmt.Sprintf("%s/src/github.com/bob", os.Getenv("GOPATH"))
> > > 			filename := strings.Replace(f.File, repopath, "", -1)
> > > 			return fmt.Sprintf("%s()", f.Function), fmt.Sprintf("%s:%d", filename, f.Line)
> > > 		},
> > > 	}
> > > 
> > > 	log.Println("hello world")
> > > }
> > > ```
> > 
> > 
> > Thank a lot of!
> > I am using path.Base, this is more universal, I think ;-)
> > ```go
> > package main
> > 
> > import (
> > 	"fmt"
> > 	"path"
> > 	"runtime"
> > 
> > 	"github.com/sirupsen/logrus"
> > )
> > 
> > func main() {
> > 	log := logrus.New()
> > 	log.SetReportCaller(true)
> > 	log.Formatter = &logrus.TextFormatter{
> > 		CallerPrettyfier: func(f *runtime.Frame) (string, string) {
> > 			filename := path.Base(f.File)
> > 			return fmt.Sprintf("%s()", f.Function), fmt.Sprintf("%s:%d", filename, f.Line)
> > 		},
> > 	}
> > 
> > 	log.Println("hello world")
> > }
> > `
> > ```
> 
> This lose coloring on console.

You're right.. Using &log.TextFormatter loses all the colors..

```go
log.SetFormatter(&log.TextFormatter{
    FullTimestamp: true,
})
```

**Comment by nimrodshn** [comment] 2023-04-18 12:48
Is there a way to do this with the file and line number added as separate fields?

**Comment by flyzhang007** [comment] 2023-04-18 12:48
您的邮件已收到，我会尽快查看&回复:)

**Comment by SharkFourSix** [comment] 2023-07-01 19:10
> Is there a way to do this with the file and line number added as separate fields?

I think the best way would be to create an instance per package and pass a custom string (package) to the formatter. At least that way you know which package the error took place in. It just adds some context instead of a spontaneous error message.

**Comment by kuchaguangjie** [comment] 2024-02-06 05:15
After set `log.SetReportCaller(true)`

The log looks like this:
```
time="2024-02-06T13:12:16+08:00" level=info msg="Server exit, bye." func=github.com/xxx/xxx/util/main_util.gracefulShutdown file="/home/eric/go/src/gitlab.com/xxx/xxx/util/main_util/main_util.go:108"
```
2 problems:
- It contains `func` and `file` part,  we only want `file` part usually.
- and call `log.SetFormatter(..)` as suggested above, doesn't make the `file` part shorter.

**Comment by flyzhang007** [comment] 2024-02-06 05:16
您的邮件已收到，我会尽快查看&回复:)
