### ISSUE TITLE
Mutex locks cause serious performance degredation

### ISSUE THREAD

**Issue by macdabby** [sirupsen/logrus#1192] opened 2020-10-23 13:21 UTC
I have an application that logs a lot of data, and during times has high concurrency. It appears that logrus becomes a bottleneck due to mutex locks. There are three in entry.go:

These two are apparently for modification of the entry itself, and I wonder if that's necessary. What would be the impact of removing these? They should not do anything to the logger itself.
https://github.com/sirupsen/logrus/blob/master/entry.go#L231
https://github.com/sirupsen/logrus/blob/master/entry.go#L260

This one is where the logs are written, and seems like, if anything, only the Logger.Out.Write() function would need this, which could be replaced more easily with other writers that did not require locking, or required less locking by means of some sort of buffer:
https://github.com/sirupsen/logrus/blob/master/entry.go#L269

**Comment by dgsb** [comment] 2020-12-27 14:36
duplicate of #1213

**Closed by dgsb** 2020-12-27 14:36 UTC
Labels: performance
