### ISSUE TITLE
Entry parallel write panic

### ISSUE THREAD

**Issue by templarzq** [sirupsen/logrus#789] opened 2018-07-18 10:49 UTC
entry.go:

func (entry *Entry) write() {
	serialized, err := entry.Logger.Formatter.Format(entry)
	entry.Logger.mu.Lock()
	defer entry.Logger.mu.Unlock()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to obtain reader, %v\n", err)
	} else {
		_, err = entry.Logger.Out.Write(serialized)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to write to log, %v\n", err)
		}
	}
}

shoud it be like this?
func (entry *Entry) write() {
	entry.Logger.mu.Lock()
	defer entry.Logger.mu.Unlock()
	serialized, err := entry.Logger.Formatter.Format(entry)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to obtain reader, %v\n", err)
	} else {
		_, err = entry.Logger.Out.Write(serialized)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to write to log, %v\n", err)
		}
	}
}

**Comment by dgsb** [comment] 2018-07-21 05:35
You're probably right. Can you provide that as a pull request so that the test suite can run on your modification ?

**Comment by dgsb** [comment] 2018-07-23 11:42
Duplicate of #703

**Closed by dgsb** 2018-07-23 11:42 UTC
Labels: bug
