### ISSUE TITLE
Expose levels as numerical codes in the entry

### ISSUE THREAD

**Issue by eexit** [sirupsen/logrus#458] opened 2016-12-19 09:58 UTC
Hello,

As the [RFC 5424](https://tools.ietf.org/html/rfc5424) specifies, it would be nice to include [the numerical codes](https://tools.ietf.org/html/rfc5424#section-6.2.1) of the level in the entry so it'd be way easier to parse logs at the end.

Is this something possible?

Thanks a lot!

**Comment by stevvooe** [comment] 2017-01-10 20:24
What do you mean? Could you give an example in relation to logrus?

**Comment by sirupsen** [comment] 2017-02-07 01:21
Duplicate of https://github.com/sirupsen/logrus/issues/355

**Closed by sirupsen** 2017-02-07 01:21 UTC
