### ISSUE TITLE
Custom Log Levels

### ISSUE THREAD

**Issue by yoiang** [sirupsen/logrus#463] opened 2017-01-08 16:15 UTC
Hello logrus folks!
It was mentioned in issue #121 that being able to make your own custom log levels would be a feature by 1.0, wanted to make a place to track the feature's progress.

Thanks for the great work!

**Comment by stevvooe** [comment] 2017-01-10 20:12
@yoiang Do you have a proposal for how this would work?

**Comment by yoiang** [comment] 2017-01-11 15:14
hey @stevvooe! Do you mean what would the API look like or how would it actually be implemented in logrus' guts technically? I am not expert with either but can take some time and figure it out depending on what you're asking!

**Comment by stevvooe** [comment] 2017-01-11 22:13
@yoiang So, the issue is that we already have values that have an ordering. Allowing users to define these may have an impact on how that ordering interacts. Without going into details, bolting this on is likely pretty complex.

@sirupsen may have a more detailed plan for how this might work.

**Comment by cretz** [comment] 2017-02-08 18:57
I suggest simply exposing `logrus.Entry.Log(Level, string)` (and `logrus.Entry.Logf(Level, string, ...interface{})`) and adding a `logrus.SetCustomLevelName(Level, string)` and `logrus.GetCustomLevelName(Level) string, bool` which are simply backed by a thread-safe map. Then `logrus.Level.String()` can use the latter before defaulting to "unknown".

Then we can all simply create levels via:

```go
const TraceLevel = logrus.DebugLevel + 1

func init() {
  logrus.SetCustomLevelName(TraceLevel, "trace")
}
```

This of course does not solve issues where people may want their level in between other levels. The way to solve that with a backwards compatible impl is to keep the `Level` type and make a new interface and what not:

```go
type Leveler interface {
  Cmp(other Leveler) int
  LevelString() string
}

func (level Level) Cmp(other Leveler) int {
  switch other := other.(type) {
    case Level:
      if level > other {
        return 1
      } else if level < other {
        return -1
      }
      return 0
    default:
      return -other.Cmp(level)
  }
}

func (level Level) LevelString() string { return level.String() }
```

Then of course have `logrus.Entry.Log(Leveler, string)` and `logrus.Entry.Logf(Leveler, string, ...interface{})`. Granted it may have a bit of performance overhead introducing a type switch in every log statement, but it's a thought. I think the first proposal is good enough to solve people's notice/trace wants (or just go ahead and acknowledge there's a level below debug for many common use cases).

**Comment by stevvooe** [comment] 2017-02-08 21:06
@cretz Would it be sufficient just to add a `Trace` level to logrus? I'm really not sure about the effect bolting something on like this.

**Comment by cretz** [comment] 2017-02-08 21:24
@stevvooe - Yes, but it has been explicitly [rejected](https://github.com/sirupsen/logrus/pull/284#issuecomment-210748707) [multiple](https://github.com/sirupsen/logrus/pull/198#issuecomment-210747238) [times](https://github.com/sirupsen/logrus/issues/121#issuecomment-73380893).

FWIW, I disagree w/ the rejections. In my lib I have `Tracef` that I just check my own level state on before just sending it off to `Debugf` which is good enough for me.

**Comment by Random-Liu** [comment] 2018-01-16 22:45
@stevvooe See you here! :D 

@cretz I agree with you. In Kubernetes, we usually have:
* One level for normal production log output (corresponds to logrus `info`)
* One level for test environment output (corresponds to logrus `debug`)
* One level for actual debug, we don't want to log this by default in the log output, because they are too spammy. But we do want to be able to see these logs when we actually see a problem, and need detailed information for debug. (corresponds to what? I think this is where `trace` is useful.)

**Comment by miguelmota** [comment] 2018-01-17 02:16
+1 for custom log levels

**Comment by IMBlues** [comment] 2018-01-19 09:20
+1 
Just like `glog.V(x)`, we could filter out most of spammy log.

**Comment by defendertx** [comment] 2019-02-08 20:40
+1 for user implemented log levels. A use case that we use a lot that might not have been considered is Cloudwatch Log filtering into Cloudwatch Metrics. In most languages we create a log level called `Metric` that is generally very high, somewhere above `Warn` or `Error` depending on the language. This way our logs that contain metrics that need to be processed are always logged in all environments without extremely verbose logs. Currently with logrus I would have to log these at `Info` or patch them into `Warn` which would be weird.

**Comment by relwell** [comment] 2019-02-13 18:54
FWIW @defendertx's comment is exactly the reason I found this issue by searching "logrus custom level" in Google

**Comment by Kigamba** [comment] 2019-10-21 20:34
+1 for custom log levels

**Comment by freeformz** [comment] 2019-10-23 01:05
Logrus now (and for a while) has had a [`Trace`](https://godoc.org/github.com/sirupsen/logrus#Trace) level and corresponding methods. That seems to address all the use cases I read through in this issue.

Additionally there are [`Log`](https://godoc.org/github.com/sirupsen/logrus#Entry.Log), [`Logf`](https://godoc.org/github.com/sirupsen/logrus#Entry.Logf), & [`Logln`](https://godoc.org/github.com/sirupsen/logrus#Entry.Logln) methods which take arbitrary levels. 

I think the only thing missing is the way that existing levels are somewhat hard coded, making extension / customization of them a bit hard. Related to that: https://github.com/sirupsen/logrus/pull/1009#issuecomment-545218036

**Comment by dm3ch** [comment] 2019-11-17 22:36
Suddenly I think Trace level fits most of needs but not all.

For example custom log levels could be useful also for audit logging, suddenly with current log levels it's very complex to find place for them, and creating custom log level for them could be a good option

**Comment by markphelps** [comment] 2020-02-25 14:57
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)

**Closed by markphelps** 2020-02-25 14:57 UTC
Labels: enhancement
