### ISSUE TITLE
Support colors on Windows 10

### ISSUE THREAD

**Issue by andrewsav-datacom** [sirupsen/logrus#820] opened 2018-09-13 03:52 UTC
I'm confused with the state of this issue. There are a couple of closed issue [here](https://github.com/sirupsen/logrus/issues/496) and [here](https://github.com/sirupsen/logrus/issues/172). 

They discuss resolving the issue then reversing the change, and then fixing it again?

Anyway it does not seem to be working for me:
![2018-09-13_15-51-37](https://user-images.githubusercontent.com/27190911/45466256-e324f080-b76c-11e8-9e30-193aefac3701.png)

Program:

```golang
package main
import (
	log "github.com/sirupsen/logrus"
)
func main() {
	log.SetFormatter(&log.TextFormatter{})
	log.Errorf("Hello World!")
}
```

run with:

```
go run main.go
```

result:

```
[31mERRO[0m[0000] Hello World!
```

What is the current status of this?

**Comment by dgsb** [comment] 2018-09-16 07:06
Hello, we do have a pending pr #741 for this issue, but I have no way to test if it works as intended. Can you checj after I've merged that it works as intended ?

**Comment by AndrewSav** [comment] 2018-09-16 07:34
@dgsb I can try but it also can take a little while. Thanks.

**Comment by AndrewSav** [comment] 2018-09-16 08:32
@dbs5 for the test case above the changes has worked on windows 10. I'll try to test on windows 7 as well and will let you know.

**Closed** 2018-09-16 08:33 UTC

**Comment by AndrewSav** [comment] 2018-09-16 08:41
@dgsb It does not work on Windows 7 though. Sorry.

**Comment by a-h** [comment] 2018-10-11 08:47
I also get control sequences rendered to the console when using PowerShell on Windows Server 2012.

<img width="701" alt="screen shot 2018-10-11 at 09 46 31" src="https://user-images.githubusercontent.com/1029947/46792162-97993e80-cd3a-11e8-9c19-888f59a4f393.png">

**Comment by AndrewSav** [comment] 2018-10-11 09:53
@a-h I have a suspicion that if you want this fixed you will be better off opening a new issue, or commenting on an issue that is not closed...

**Comment by dgsb** [comment] 2018-10-11 11:10
indeed, please open new issues otherwise it gets very hard to track
