### ISSUE TITLE
showing the time on TTY output

### ISSUE THREAD

**Issue by digininja** [sirupsen/logrus#896] opened 2019-01-26 20:25 UTC
In the README you say:

```
Besides the fields added with WithField or WithFields some fields are automatically added to all logging events:

time. The timestamp when the entry was created.
```

But in the TTY output, the time isn't shown. Do I need to use a field to show the time or is there a way to enable it to be shown like it is in the normal log package?

**Comment by richpoirier** [comment] 2019-01-29 19:02
Hi @digininja. Can you paste the setup code you've used for logrus? The time field should be there unless you set `DisableTimestamp` to `true` on the formatter.

**Comment by digininja** [comment] 2019-01-29 19:38
This is the code:

https://play.golang.org/p/PShICVpltjs

And this is what I see:

![log](https://user-images.githubusercontent.com/117081/51935116-11922800-23fd-11e9-8b28-0ad1b1cf0941.png)

This is the type of thing I'm after from the built in logger:

```
Begin...
2019/01/29 19:36:52 Print level message: 1
```

I'm writing a script that will be left running over a few days and I'd like to be able to match timestamps to things happening in case anything goes wrong.

**Comment by dgsb** [comment] 2019-02-10 14:06
You do have the timestamp in your trace these are the `[0000]` which indicates the number of seconds elapsed since the start of your process.
If you want something clearer you can set the FullTimestamp field of the TextFormatter to true.
If you want to customize the layout of your timestamp you can set also the field `TimestampFormat` of the text formatter. The value of this field is something which need to be understood by `time.Time.Format`

**Comment by dgsb** [comment] 2019-02-23 08:22
Closing. Not a bug.

**Closed by dgsb** 2019-02-23 08:22 UTC
Labels: question

**Comment by digininja** [comment] 2019-02-23 08:27
Thanks, will give it a try.
