### ISSUE TITLE
log.Printf() and log.Infof append a newline to the output

### ISSUE THREAD

**Issue by heipei** [sirupsen/logrus#167] opened 2015-04-14 20:17 UTC
I just started using logrus by replacing the import for log. Previously I had used log.Printf("bla\n") to log messages, but logrus appends an extra \n so that there is an empty line after each log message. What am I missing? If this is supposed to be API-compatible, this should behave differently.

**Comment by shearn89** [comment] 2015-06-24 13:57
I would also be interested in this, would be nice to be able to print progress messages without a newline.

**Comment by omeid** [comment] 2015-08-21 04:47
+1 I would love this feature too. Perhaps this can be built as a formatter?

**Comment by Sirupsen** [comment] 2015-08-23 18:06
You're right, with the text formatter this is not API-compatible, this is rather inherent to field-logging the way I see it.

**Comment by Sirupsen** [comment] 2015-10-05 11:54
This has come up again. I'm thinking we should escape the character instead. It doesn't make sense with the current formatters to actually do a newline.

**Comment by nomuna** [comment] 2017-02-21 11:05
Looks like a duplicate of #167, if I am not mistaken.

**Comment by nomuna** [comment] 2017-02-21 11:07
Looks like a duplicate of #278.

**Closed** 2018-08-26 09:06 UTC
Labels: bug

**Comment by universam1** [comment] 2019-10-30 09:58
I'd like to see this #674 674 as an option
