### ISSUE TITLE
How to get file/line number ?

### ISSUE THREAD

**Issue by frranck** [sirupsen/logrus#843] opened 2018-10-16 07:38 UTC
Hello,
Is there an easy way to get file/line number in error ? 
Wouldn't anyone need that as a default ?

**Comment by dgsb** [comment] 2018-10-16 11:42
duplicate of #63

**Closed by dgsb** 2018-10-16 11:43 UTC

**Comment by trinhhuong244** [comment] 2020-10-23 19:00
formatter := runtime.Formatter{ChildFormatter: &log.TextFormatter{
		FullTimestamp: true,
	}}
	formatter.Line = true
	log.SetFormatter(&formatter)
	log.SetOutput(os.Stdout)
	log.SetLevel(log.InfoLevel)
	log.WithFields(log.Fields{
		"file": "main.go",
	}).Info("Server is running...")
Note: import ( 	runtime "github.com/banzaicloud/logrus-runtime-formatter"
	log "github.com/sirupsen/logrus")
