### ISSUE TITLE
Feature request: logrus.SetLevel(MuteLevel)

### ISSUE THREAD

**Issue by dreh23** [sirupsen/logrus#622] opened 2017-08-17 11:35 UTC
Is there a simple way to silence output. If not I would suggest a new loglevel: MuteLevel/QuietLevel/SilentLevel.

This log level will skip any output. What do you think?

**Comment by dmathieu** [comment] 2017-08-17 12:05
Why do any logging if it's to be entirely silenced?

**Comment by dmathieu** [comment] 2017-08-17 12:06
This is also not a standard used anywhere else in Go. For that reason, I'm :-1:

**Comment by dreh23** [comment] 2017-08-17 12:21
> Why do any logging if it's to be entirely silenced?

My use case would be a command line switch to silence output. This is quite common.

**Comment by dmathieu** [comment] 2017-08-17 12:23
You can send all output to `/dev/null` then.

**Comment by dreh23** [comment] 2017-08-17 12:41
I believe a global switch to log inside logrus can be useful without using shellfoo or crippling the logging functionality when you need it. If adding this log level breaks common behavior maybe we can add another switch without touching log levels.

**Comment by dreh23** [comment] 2017-09-06 13:09
There is a discussion on [stackexchange](https://unix.stackexchange.com/questions/191254/why-do-many-commands-provide-a-quiet-option) on why quiet/silence flags can be useful. I would like to easily implement a mute switch with logrus.

**Comment by dgsb** [comment] 2018-09-16 14:04
duplicate of #441

**Closed by dgsb** 2018-09-16 14:04 UTC
