### ISSUE TITLE
Report Caller returns logrus files/functions with Go 1.14Beta1

### ISSUE THREAD

**Issue by nabowler** [sirupsen/logrus#1089] opened 2020-01-17 13:51 UTC
In Go 1.14Beta1, the file and function information logged when ReportCaller is set to true reports logrus code, not the calling code.

## POC

```go
package main

import "github.com/sirupsen/logrus"

func init() {
	logrus.SetReportCaller(true)
	logrus.Info("Logging from init")
}

func main() {
	logrus.Info("Logging from main")
	foo()
}

func foo() {
	logrus.Info("Logging from foo")
}
```

### 1.13.6 Output
INFO[0000]/tmp/poc/main.go:7 main.init.0() Logging from init                            
INFO[0000]/tmp/poc/main.go:13 main.main() Logging from main                            
INFO[0000]/tmp/poc/main.go:19 main.foo() Logging from foo

### 1.14Beta1 Output
INFO[0000]/home/nzb301/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() Logging from init                            
INFO[0000]/home/nzb301/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() Logging from main                            
INFO[0000]/home/nzb301/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() Logging from foo

**Comment by dgsb** [comment] 2020-02-25 17:28
thanks @nabowler for your report.
It seems it is a duplicate of #1096

**Comment by onoketa** [comment] 2020-02-27 02:11
Same problem

**Closed** 2020-03-06 10:24 UTC

**Comment by Ponewor** [comment] 2020-11-10 00:40
It still happens in Go 1.15.

**Comment by gonejack** [comment] 2020-11-20 07:44
It still happens in Go 1.15.

**Comment by gonejack** [comment] 2020-11-20 07:49
Oh, I forgot to upgrade to 1.7.0.
