### ISSUE TITLE
no way to write log to a file!

### ISSUE THREAD

**Issue by HomeGamer19880330** [sirupsen/logrus#414] opened 2016-09-20 03:28 UTC
logger := logrus.New()
fp, err = os.OpenFile(logFilePath, os.O_CREATE|os.O_APPEND|os.O_RDWR, 0666)
logger.Out = bufio.NewWriterSize(fp, maxFileSize)

code like this,I run the program happy

but!
I can not write log to file!why it is?

how could it possilbe???

**Comment by HomeGamer19880330** [comment] 2016-09-20 03:38
any way.... is there a example to show how to write log to a local file?thanks!

**Comment by chennqqi** [comment] 2016-09-21 12:23
@HomeGamer19880330 
My code may help you 

	logrus.SetLevel(logrus.ErrorLevel)
	var f *os.File
	var err error
	if f, err = os.Create(APPNAME + ".log"); err != nil {
		logrus.Error("creat log failed", err)
		return
	}
	//close log
	logrus.SetOutput(f)
	defer func(f *os.File) {
		f.Sync() //look here
		f.Close()
	}(f)

**Comment by proudlily** [comment] 2016-10-02 09:41
@chennqqi as far as i know,if using the way that you offered,we cant use Field into the logFile,only a sentence.

**Comment by stevvooe** [comment] 2016-11-23 04:31
`Logger.Out` should do the trick but I haven't confirmed it. Did you call flush on the buffered writer?

Looks like this is a duplicate of #410.

**Comment by sirupsen** [comment] 2017-02-07 00:46
https://github.com/sirupsen/logrus/pull/471 fixes this with a README entry

**Closed by sirupsen** 2017-02-07 00:46 UTC
