### ISSUE TITLE
use of internal package github.com/sirupsen/logrus/internal/terminal not allowed

### ISSUE THREAD

**Issue by pacmessica** [sirupsen/logrus#933] opened 2019-03-28 10:10 UTC
breaking change was introduced yesterday. I see the following error on all my builds:

```
../../../github.com/Sirupsen/logrus/terminal_check_notappengine.go:9:2: use of internal package github.com/sirupsen/logrus/internal/terminal not allowed
```

**Comment by artagel** [comment] 2019-03-28 12:29
Same issue.

**Comment by dgsb** [comment] 2019-03-28 13:31
It's kind of unexpected.
Can you provide more context, or even better a code sample using logrus which exhibits the build break ?
Which go version are you using ?
On a sidenote,  I highly recommend that you use tagged version instead of the tip master.

**Comment by lavoiesl** [comment] 2019-03-28 13:45
I merged #935 for the time being, just so users aren't blocked, but let's keep this one open to figure out why.

**Comment by artagel** [comment] 2019-03-28 13:48
I’ll be able to get full details when I get back home. 
I’m using https://github.com/vouch/vouch-proxy
You can’t specify the tag version when using go get, so I ended up pulling the repo and checking out the tag in my gopath src. This obviously isn’t a long term solution.

**Comment by dgsb** [comment] 2019-03-28 13:50
@artagel you may want to use dep https://golang.github.io/dep/ for managaing your project dependencies.
Or you use the next gen dependency manager through modules.
So that you don't rely on master anymore.

**Comment by artagel** [comment] 2019-03-29 13:35
Yeah, I think this is an issue golang needs to solve better.  Dep is being abandoned as far as I've read, and they are trying to put out something new.

**Comment by dgsb** [comment] 2019-03-29 14:35
@pacmessica or @artagel can you provide more feedback on how to reproduce the issue ? because our temporary forces us to expose an API we do not want to make public.

**Comment by artagel** [comment] 2019-03-29 14:45
Sure, 
The push you guys did yesterday fixed the issue for now...  
I still have a copy of the master from before that fix...this is what happens:
But using vouch-proxy as an example:
git clone https://github.com/vouch/vouch-proxy
cd vouch-proxy
go get -v 
go run main.go 
../../Sirupsen/logrus/terminal_check_notappengine.go:9:2: use of internal package not allowed

The problem seems to be the use of the word internal in your import.
Check out: 
https://golang.org/cmd/go/#hdr-Internal_Directories
https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit

**Comment by tandr** [comment] 2019-03-29 16:12
Well... usage of internal was intentional. At this point we can as well put it under main directory and get rid of exported IsTerminal altogether.

@artagel 
There are testutils under `internal` already, and you are not using it but still have in a codebase - because otherwise it would be broken as well.

Also... It became a lowercase `sirupsen` (as outlined in a second paragraph of a README file) quite a while ago. Makes me wonder if your codebase is pulling a correct references to it.

**Comment by artagel** [comment] 2019-03-30 06:23
@tandr 
I've changed all imports from Sirupsen to sirupsen, and you are correct, with the original version that had the internal tag, it no longer throws this error. 
vouch isn't my project, but I've submitted a pull request to fix this.
Pull request for reference: https://github.com/vouch/vouch-proxy/pull/88

**Comment by dgsb** [comment] 2019-04-01 12:32
thanks @artagel for your feedback.
@pacmessica can you also provide some context on how to reproduce the issue, we suspect something is wrong with your environment, but we would like to be sure.

**Comment by dgsb** [comment] 2019-04-02 15:45
the package has been removed and associated functions moved as private one in #943

**Closed by dgsb** 2019-04-02 15:45 UTC
Labels: need-more-info
