### ISSUE TITLE
Split TextFormatter into a ColorTerminalFormatter and a pure TextFormatter; add a TextFormatterBuilder

### ISSUE THREAD

**Issue by dolmen** [sirupsen/logrus#296] opened 2015-11-20 14:37 UTC
The current `TextFormatter` does too much, and its `Format()` method does too much redundant checks at each call (for example, on every call [it checks if the OS is Windows](../blob/9ca7d9fefe4ee54e2d6f53ea26b84e5d5bc694f0/text_formatter.go#L73)).
The core reason is that at least 2 formatters should be defined instead of one.

In fact, an efficient `Formatter` would have no options at all, and espcially no option that can be changed once it is in use. Because a formatter should have consistent behaviour for the log to be parsable.

Here is my proposal:
- transform the current `TextFormatter` type into a `TextFormatterBuilder` with a `Build()` method that return a dedicated, efficient `Formatter`
- `isTerminal` should be checked just once. As a first this could be
- a pure `TextFormatter` would do the basic formatting of the current `TextFormatter{DisableColors: true}`
- a `ColorTerminalFormatter` would do the same as the current `TextFormatter{ForceColors: true, DisableColors: false}`

The ColorTerminalFormatter implementation could even be specialized by operating system (to handle the Windows special case).

**Comment by dolmen** [comment] 2015-11-20 14:59
I think that a `FormatterBuilder` interface should even be added to the API because the TextFormatter example shows that to be able to create an appropriate Formatter, a builder must be aware of the output Writer: currently the `IsTerminal()` check is hard coded to STDOUT, even if the output of the `TextFormatter` is a different Writer.

```go
type FormatterBuilder interface {
    Build(out io.Writer, minimumLevel Level) Formatter
}
```

**Comment by Sirupsen** [comment] 2015-11-23 08:13
This is planned for 1.0. Thanks for your report.

**Comment by dolmen** [comment] 2015-12-04 16:13
Does that mean that you are interested in a PR implementing my proposal?

**Comment by piotr1212** [comment] 2016-01-11 09:49
This sounds like a good improvement. I'm now trying to get the TextFormatter print lines in the same format as the colored output but without the colors. I don't think this is possible with current implementation. All I get is the logfmt kv output.

**Comment by dolmen** [comment] 2016-01-31 23:44
I've implemented this API change, but in a less disruptive way than what I originally thought. The code is in my [FormatterFactory branch](/Sirupsen/logrus/compare/master...dolmen:FormatterFactory) on [my fork](/dolmen/logrus/commits/FormatterFactory): I've been able to *mostly* preserve source compatibilty for clients of the existing API.
The major API change is only for custom formatters. See the [updated README about Formatters](/dolmen/logrus/blob/61b8d26761d9e07d3517fee020304810cefd1f00/README.md#formatters).

**Comment by dgsb** [comment] 2018-10-12 04:48
Duplicate of #136

**Closed by dgsb** 2018-10-12 04:48 UTC
Labels: 1.0/rewrite
