### ISSUE TITLE
When in Debug level, print structs with name:value pairs instead only values

### ISSUE THREAD

**Issue by labkode** [sirupsen/logrus#166] opened 2015-04-11 16:48 UTC
To help debugging it would be great to print this pair instead only the values.
It should be similar to use fmt.Printf("%+v", myStruct).

**Comment by eproxus** [comment] 2015-04-28 13:14
Would love functionality to override this on other log levels as well.

**Comment by dgsb** [comment] 2018-10-09 04:34
Duplicate of #609

**Closed by dgsb** 2018-10-09 04:34 UTC
Labels: enhancement
