### ISSUE TITLE
logger.Writer()

### ISSUE THREAD

**Issue by Incisive** [sirupsen/logrus#174] opened 2015-05-07 14:14 UTC
I'm having an issue getting the io.Writer from a logger.

I have a io.MultiWriter that i set as the output of logrus.  Inside that io.MultiWriter I have a rotating file system that writes to a file on disk, and then os.Stdout.  What I want to accomplish is to have another instance of logrus in place of my rotating file writer, that way I can have a JSONFormatter and not the terminal style text when a TTY is attached.  Here is the error I'm getting when trying to grab the io.Writer per the documentation on the readme:

```
main.init·2: call to external function github.com/Sirupsen/logrus.(*Logger).Writer
main.init·2: github.com/Sirupsen/logrus.(*Logger).Writer: not defined
main.init·2: undefined: github.com/Sirupsen/logrus.(*Logger).Writer
make: *** [run] Error 2
```

Any assistance will be greatly appreciated.

**Comment by abourget** [comment] 2015-12-18 16:25
It's not 100% clear what you mean.  You have two Logger instances, or only one that you configure when you're in a terminal ?

what about something like:

    if !log.IsTerminal() {
		logFile, err := os.Create("filename.log")
		if err != nil {
			log.Warnf("Couldn't open log-file, falling back to stdout: %s", err)
		} else {
			log.SetFormatter(&log.JSONFormatter{})
			log.SetOutput(logFile)
		}
    }

?

**Comment by aybabtme** [comment] 2016-04-16 08:14
@Incisive I'm not sure what the problem is here. Can you show with code what you're trying to achieve?

**Comment by stevvooe** [comment] 2017-01-30 22:23
This looks like an import problem or some development environment setup issue. Since it has been in need-more-info for awhile, I am going to go ahead and close this issue.

**Closed by stevvooe** 2017-01-30 22:23 UTC
Labels: need-more-info
